site_name: Python开发栈
#site_name: Python博客栈
#site_name: Python开发栈-Python全栈开发-国内Python开发者网络社区
# 设置站点的规范URL。这将添加带有规范URL的链接标记到生成的HTML标头。
site_url: https://pythoneers.cn
site_author: Erics
# 站点描述
site_description: 'Python开发栈是一个专为以Python为首要编程语言、计划或已经从事Python工作的工程师，以及Python感兴趣的任何人群免费提供文档学习、资料共享的平台。'
#copyright: docs.xiaolangren.cn
site_dir: site
docs_dir: 'docs'
extra_css:
  - css/nav.css
  - css/public.css
use_directory_urls: false
extra_javascript:
  - js/main.js
  #  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
  #  - js/busuanzi.pure.mini.js
  - js/gotop.js
  - js/baiducount.js
plugins: [ ]
#repo_url: https://github.com/example/repository/
extra:
  version: 0.10.0
#设置版权信息以包含在主题的文档中
copyright: null
#设置Google Analytics跟踪配置。
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
nav:
  #  - 主页: index.md
  - Python:
      - Python基础: python/python-basis.md
      - Python进阶: python/python-advance.md
      - Python高级: python/python-senior.md
      #      - Python零碎知识点整理: python/python3-general-knowledge.md
      - Python内置模块: python/built-in-module.md
      - Python第三方模块: python/external-module.md
      #      - 面试题题解: python/interview.md
      - Python数据结构与算法: python/algorithm.md
      - Python设计模式: python/design-pattern.md
      - Python办公自动化: python/office-automation.md
      #      - 算法基础: python/algorithm.md
      - Python核心知识: python/interviews-python.md
      - Python网络相关知识: python/interviews-network.md
      - 剑指Offer刷题: python/nowcoder-sword-offer.md
      - Leetcode算法刷题: python/leetcode-algorithm.md
      - Leetcode数据库刷题: python/leetcode-db.md
      - Leetcode多线程刷题: python/leetcode-multithreading.md
  - Python Web:
      - Flask基础: python-web/flask.md
      - Flask核心知识: python-web/interviews-flask.md
      - Flask实战篇: python-web/project-flask.md
      - Django基础: python-web/django.md
      - Django核心知识: python-web/interviews-django.md
      - Django实战篇: python-web/project-django.md
      - DRF基础: python-web/drf.md
      - Celery异步框架: python-web/celery.md
  #      - 代码统计系统(Flask): python-web/codecount.md
  #      - 在线课程学习系统(Django): python-web/course-learn.md
  #      - 社会活动问卷调查系统(DRF+Vue): python-web/social-activities-questionnaire.md
  #      - 个人网站系统(DRF+Vue): python-web/my-site.md
  #      - 面试题题解: python-web/interview.md
  - Python GUI:
      - PyQt5: gui/pyqt5.md
  - 网络爬虫:
      #      - Requests: web-crawler/requests.md
      - Scrapy: web-crawler/scrapy.md
  - 数据分析:
      - NumPy: data-analysis/numpy.md
      - Pandas: data-analysis/pandas.md
      - Matplotlib: data-analysis/matplotlib.md
  - 计算机视觉:
      - OpenCV: computer-vision/opencv.md
  - 机器学习:
      #      - 机器学习中的数学: machine-learning/math.md
      #      - 机器学习中的算法: machine-learning/machine-learning-algorithm.md
      #      - Sklearn:
      - 机器学习与量化交易: machine-learning/quantitative-trading.md

  - 深度学习:
      #      - CNN: deep-learning/tensorflow.md
      #      - RNN: deep-learning/tensorflow.md
      - TensorFlow: deep-learning/tensorflow.md
markdown_extentions:
  - admonition
theme:
  name: mkdocs
  custom_dir: custom_theme
  # JavaScript库在代码块中突出显示源代码。 默认值：True。
  #  highlightjs: true
  #  hljs_languages:
  #      - yaml
  #      - rust
  #      - python
  #      - shell
  #      - shell script
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s